# render.yaml (no previews block)
envVarGroups:
  - name: chatwoot-common
    envVars:
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: INSTALLATION_ENV
        value: docker
      - key: FRONTEND_URL
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: MAILER_SENDER_EMAIL
        sync: false
      - key: SMTP_ADDRESS
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_AUTHENTICATION
        value: "plain"
      - key: SMTP_ENABLE_STARTTLS_AUTO
        value: "true"
      - key: ACTIVE_STORAGE_SERVICE
        value: local

databases:
  - name: chatwoot-db
    plan: free

services:
  - type: keyvalue
    name: chatwoot-redis
    plan: free
    ipAllowList: []

  - type: web
    name: chatwoot-web
    runtime: docker
    plan: starter
    healthCheckPath: /
    #preDeployCommand: "bundle exec rails db:chatwoot_prepare"
    dockerCommand: /bin/sh -c "/app/docker/entrypoints/rails.sh bundle exec rails s -p $PORT -b 0.0.0.0"
    envVars:
      - fromGroup: chatwoot-common
      - key: DATABASE_URL
        value: "postgres://chatwoot_db_qlmk_user:kEUg79ANN4uUt4A4VFKxI6WFGK70NIlP@dpg-d2l0ds95pdvs73a6le4g-a:5432/chatwoot_db_qlmk?sslmode=require" 
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: chatwoot-redis
          property: connectionString
      - key: POSTGRES_HOST
        value: "dpg-d2l0ds95pdvs73a6le4g-a"
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: "chatwoot_db_qlmk"
      - key: POSTGRES_USERNAME
        value: "chatwoot_db_qlmk_user"
      - key: POSTGRES_PASSWORD
        value: "kEUg79ANN4uUt4A4VFKxI6WFGK70NIlP"
    disk:
      name: chatwoot-uploads
      mountPath: /app/storage
      sizeGB: 5

  - type: worker
    name: chatwoot-worker
    runtime: docker
    plan: starter
    dockerCommand: "/bin/sh -lc 'bundle exec rails db:seed --trace && bundle exec rails db:migrate --trace && echo DB_ready && sleep 600'"
    envVars:
      - fromGroup: chatwoot-common
      - key: DATABASE_URL
        value: "postgres://chatwoot_db_qlmk_user:kEUg79ANN4uUt4A4VFKxI6WFGK70NIlP@dpg-d2l0ds95pdvs73a6le4g-a:5432/chatwoot_db_qlmk?sslmode=require"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: chatwoot-redis
          property: connectionString
      - key: POSTGRES_HOST
        value: "dpg-d2l0ds95pdvs73a6le4g-a"
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: "chatwoot_db_qlmk"
      - key: POSTGRES_USERNAME
        value: "chatwoot_db_qlmk_user"
      - key: POSTGRES_PASSWORD
        value: "kEUg79ANN4uUt4A4VFKxI6WFGK70NIlP"
